/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.parapuan;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * @author spring
 */
public class Istatistikler extends javax.swing.JFrame {

    /**
     * Creates new form Istatistikler
     */
    Connection connection = Veritabani.getConnection();

    public Istatistikler() {
        initComponents();
        kullanicipaneli.setVisible( false );
        hata.setVisible( false );
        odemestate.setVisible( false );
        setDefaultCloseOperation( javax.swing.WindowConstants.DISPOSE_ON_CLOSE );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kullanicipaneli = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        isim = new javax.swing.JLabel();
        parapuan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        referans = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        miktar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        odemestate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        zincir = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        refs = new javax.swing.JLabel();
        combom = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        hata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel3.setText("Adı soyadı :");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel4.setText("Para Puanı :");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel5.setText("Referans No :");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel6.setText("Miktar :");

        miktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miktarActionPerformed(evt);
            }
        });

        jButton2.setText("Öde");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        odemestate.setText("Başarılı Ödeme.");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel7.setText("Zincir Sayısı :");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel8.setText("Referans Sayısı :");

        refs.setText("jLabel9");

        javax.swing.GroupLayout kullanicipaneliLayout = new javax.swing.GroupLayout(kullanicipaneli);
        kullanicipaneli.setLayout(kullanicipaneliLayout);
        kullanicipaneliLayout.setHorizontalGroup(
            kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanicipaneliLayout.createSequentialGroup()
                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullanicipaneliLayout.createSequentialGroup()
                        .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(17, 17, 17)
                        .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parapuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zincir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kullanicipaneliLayout.createSequentialGroup()
                                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(odemestate)
                                    .addGroup(kullanicipaneliLayout.createSequentialGroup()
                                        .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 79, Short.MAX_VALUE))))
                    .addGroup(kullanicipaneliLayout.createSequentialGroup()
                        .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kullanicipaneliLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(refs))
                            .addComponent(combom, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kullanicipaneliLayout.setVerticalGroup(
            kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanicipaneliLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(isim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(parapuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(referans))
                .addGap(12, 12, 12)
                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zincir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(refs))
                .addGap(18, 18, 18)
                .addComponent(combom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(kullanicipaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(14, 14, 14)
                .addComponent(odemestate)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("İSTATİSTİKLER");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setText("Telefon Numarası:");

        jButton1.setText("Ara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(refno, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        hata.setForeground(new java.awt.Color(229, 42, 42));
        hata.setText("Kullanıcı Bulunamadı");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 149, Short.MAX_VALUE)
                    .addComponent(hata)
                    .addGap(0, 150, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(hata)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullanicipaneli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullanicipaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean durum = true;
        float miktarint = 0;
        try {
            miktarint = Float.parseFloat( miktar.getText() );
        } catch (Exception e) {
            System.out.println( "bir hata var" );
            durum = false;
        }
        if ( durum ) {
            durum = false;
            if ( miktarint <= Float.parseFloat( parapuan.getText() ) ) {
                System.out.println( "evvvet " );
                try {
                    System.out.println( referans.getText() );
                    PreparedStatement preparedStatement = connection.prepareStatement( "update musteri set parapuan=parapuan-? where numara=?" );
                    preparedStatement.setFloat( 1, miktarint );
                    preparedStatement.setString( 2, "+90" + refno.getText() );

                    durum = !preparedStatement.execute();

                    parapuan.setText( sevr( Float.parseFloat( parapuan.getText() ) - miktarint ) );
                    preparedStatement.close();

                } catch (Exception ex) {

                }

            }
        }
        setdurum( durum );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void miktarActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_miktarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miktarActionPerformed

    private void jButton1ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean durum = false;
        hata.setVisible( false );
        String referansno = refno.getText();
        kullanicipaneli.setVisible( false );
        boolean isnumber = true;
        String phone = "+90";

        Pattern p = Pattern.compile( "^5+[0-9]{2}[0-9]{3}[0-9]{2}[0-9]{2}" );
        Matcher matcher = p.matcher( referansno );
        isnumber = matcher.matches();

        if ( isnumber ) {

            phone += referansno;
            try {
                PreparedStatement prepareStatement = connection.prepareStatement( "select name,parapuan,referansno  from musteri where numara =?" );

                prepareStatement.setString( 1, phone );
                ResultSet executeQuery = prepareStatement.executeQuery();
                if ( executeQuery.next() ) {
                    isim.setText( executeQuery.getString( 1 ) );
                    parapuan.setText( String.valueOf( executeQuery.getFloat( 2 ) ) );
                    int aInt = executeQuery.getInt( 3 );
                    referans.setText( String.valueOf( aInt ) );

                    setzincir( aInt );
                    durum = true;

                } else {
                    durum = false;
                }
                prepareStatement.close();
                executeQuery.close();
            } catch (SQLException ex) {
                Logger.getLogger( Istatistikler.class.getName() ).log( Level.SEVERE, null, ex );
            }
        }
        setScreenstate( durum );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setScreenstate( boolean a ) {
        if ( a ) {
            kullanicipaneli.setVisible( true );
        } else {
            hata.setVisible( true );
            kullanicipaneli.setVisible( false );
        }
    }

    private void setdurum( boolean durum ) {

        if ( durum ) {
            odemestate.setText( "Ödeme başarıyla tamamlandı." );
            odemestate.setForeground( Color.BLUE );
        } else {
            odemestate.setText( "Ödeme esnasında bir sorun çıktı" );
            odemestate.setForeground( Color.RED );
        }

        odemestate.setVisible( true );
    }

    private String sevr( float f ) {

        DecimalFormat df = new DecimalFormat( "#.#" );
        return df.format( f );

    }

    private List<Integer> findbyphonenumber() {
        List<Integer> ss = new ArrayList<>();
        try {
            PreparedStatement prepareStatement = connection.prepareStatement( "select referansno,name from musteri where referansolan = (select referansno from musteri where numara=?)" );
            prepareStatement.setString( 1, "+90" + refno.getText() );
            ResultSet executeQuery = prepareStatement.executeQuery();
            System.out.println("worked");
            while (executeQuery.next()) {
                ss.add( executeQuery.getInt( 1 ) );
                String string = executeQuery.getString(2);
                System.out.println(string);
                if(string!=null)
                 combom.addItem(string);
            }
            prepareStatement.close();
            executeQuery.close();

            return ss;
        } catch (SQLException ex) {
            Logger.getLogger( Istatistikler.class.getName() ).log( Level.SEVERE, null, ex );
        }

        return null;
    }
    
    private List<Integer> findbyref( int ref ) {


        List<Integer> ss = new ArrayList<>();
        try {
            PreparedStatement prepareStatement = connection.prepareStatement( "select referansno from musteri where referansolan = ?" );
            prepareStatement.setInt( 1, ref );
            ResultSet executeQuery = prepareStatement.executeQuery();
            while (executeQuery.next()) {
                ss.add( executeQuery.getInt( 1 ) );
                
            }
            prepareStatement.close();
            executeQuery.close();

            return ss;
        } catch (SQLException ex) {
            Logger.getLogger( Istatistikler.class.getName() ).log( Level.SEVERE, null, ex );
        }

        return null;
    }
    private String isims="";
    private void setzincir( int aint ) {

        List<Integer> firstchain = findbyphonenumber();
        
        refs.setText(String.valueOf(firstchain.size()));
        List<List<Integer>> secondchain = new ArrayList<>();
        int a = 12;
        firstchain.forEach( e -> {
            List<Integer> findbyref = findbyref( e );
            secondchain.add( findbyref );

        } );
        List<Integer> secondchain1 = secondchain.stream().flatMap( Collection::stream ).collect( Collectors.toList() );
        List<List<Integer>> third = new ArrayList<>();
        secondchain1.forEach( e -> {
            third.add( findbyref( e ) );
        } );
        List<Integer> thirdrealchain = third.stream().flatMap( Collection::stream ).collect( Collectors.toList() );
        System.out.println(secondchain1);
        System.out.println(thirdrealchain);
        int realsize = thirdrealchain.size() + firstchain.size() + secondchain1.size();
        zincir.setText( String.valueOf( realsize ) );

    }

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger( Istatistikler.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger( Istatistikler.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger( Istatistikler.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger( Istatistikler.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Istatistikler().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combom;
    private javax.swing.JLabel hata;
    private javax.swing.JLabel isim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel kullanicipaneli;
    private javax.swing.JTextField miktar;
    private javax.swing.JLabel odemestate;
    private javax.swing.JLabel parapuan;
    private javax.swing.JLabel referans;
    private javax.swing.JTextField refno;
    private javax.swing.JLabel refs;
    private javax.swing.JLabel zincir;
    // End of variables declaration//GEN-END:variables
}
