/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.parapuan;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author spring
 */
public class Odemeyap extends javax.swing.JFrame {

    private static float birim = Constants.birim;
    
    public Odemeyap() {
        initComponents();
        basarili.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
        Connection connection = Veritabani.getConnection();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        telno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tutar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        basarili = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 24)); // NOI18N
        jLabel3.setText("ÖDEME YAP");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Telefon Numarası :");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Ürün Tutarı :");

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton1.setText("Ödeme Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        basarili.setText("Ödeme başarıyla yapıldı");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(basarili)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(basarili)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telno, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(tutar))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validata(String telefonnumarasi,String tuta) {
       
        Pattern p = Pattern.compile("^5+[0-9]{2}[0-9]{3}[0-9]{2}[0-9]{2}");
        Matcher matcher = p.matcher(telefonnumarasi);
        if(!matcher.matches())
            return false;
        try {
            Float.parseFloat(tuta);
        }catch (Exception ex) {
            return false;
        }
       return true;
       }
    private void yenile() {
        birim=Constants.birim;
    }
    boolean exist=false;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            yenile();
                       
            String telefonnumarasi = telno.getText();
           
            String tuta = tutar.getText();    
            boolean durum=false;
            boolean isvalid=validata(telefonnumarasi,tuta);
            if (!isvalid) {
                exist=true;
            }
            if(isvalid) {
                telefonnumarasi="+90"+telefonnumarasi;
                 exist = isexist(telefonnumarasi);
               
                if(exist) {
                    float yenitutar=Float.parseFloat(tuta);
                    save(telefonnumarasi,yenitutar);
                    adminpayiver(yenitutar);
                    updateparapuan(yenitutar, telefonnumarasi); // kendi payini verme
                    referanslarıbul(telefonnumarasi,yenitutar);
                    /// .....
                    
                    
                    durum=true;
                   
                }   
                
                
                
            }
            System.out.println("exist+"+exist);
            if(durum ){
            
            basarili.setText("Ödeme Başarıyla yapıldı. ");
            basarili.setForeground(Color.BLUE);
            }
            else if(!exist){
                basarili.setText("Kayıtlı üye bulunamadı");
                basarili.setForeground(Color.RED);
            }
            else {
                basarili.setText("Uygun Parametreler Giriniz .");
                basarili.setForeground(Color.RED);
            }
            basarili.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void adminpayiver(float miktar) {
    
      
       updateparapuan(miktar, "+905383090456");
    
    }
    
    
    
 
    
    private void updateparapuan (float miktar,String telno) {
        try {
            System.out.println(birim);
            PreparedStatement st = connection.prepareStatement("update musteri set parapuan = parapuan+? where numara=?");
            st.setFloat(1,  (miktar * birim / 100));
            st.setString(2, telno);
            st.execute();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(Odemeyap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
     private void updateparapuanwithrefnum (float miktar,int uyeno) {
        try {
            PreparedStatement st = connection.prepareStatement("update musteri set parapuan = parapuan+? where referansno=?");
            st.setFloat(1,  (miktar * birim / 100));
            st.setInt(2, uyeno);
            st.execute();
            st.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Odemeyap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void save(String telno,float tutar) {
        
            try {
            
            PreparedStatement preparedStatement=connection.prepareStatement("insert into odemeler(tarih,tutar,telno) values(?,?,?)");
            preparedStatement.setTimestamp(1, new Timestamp(System.currentTimeMillis()));
            preparedStatement.setFloat(2, tutar);
            preparedStatement.setString(3, telno);
            preparedStatement.execute();
             preparedStatement.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Odemeyap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private boolean  isexist (String phonenumber)  {
        
        try {
            PreparedStatement prepareStatement = connection.prepareStatement("select * from musteri where numara=?");
            
            prepareStatement.setString(1, phonenumber);
            
            ResultSet executeQuery = prepareStatement.executeQuery();
            if(executeQuery.next()) {
                return true;
            }
            executeQuery.close();
             prepareStatement.close();
            return false;
        } catch (SQLException ex) {
            Logger.getLogger(Odemeyap.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odemeyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odemeyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odemeyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odemeyap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odemeyap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basarili;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField telno;
    private javax.swing.JTextField tutar;
    // End of variables declaration//GEN-END:variables

    private void referanslarıbul(String telno,float yenitutar) {
        try {
            PreparedStatement st = connection.prepareStatement("select referansolan as pd from musteri where numara=?");
            st.setString(1, telno);
            ResultSet executeQuery = st.executeQuery();
            int ilkref=0;
            if(executeQuery.next()) {
                ilkref=executeQuery.getInt("pd");
                
            }
            st.close();
            executeQuery.close();
            
            PreparedStatement st1 = connection.prepareStatement("select referansolan as pd from musteri where referansno=?");
            st1.setInt(1, ilkref);
            ResultSet executeQuery1 = st1.executeQuery();
            int ikinciref=0;
            if(executeQuery1.next()) {
                ikinciref=executeQuery1.getInt("pd");
                
            }
            st1.close();
            executeQuery1.close();


            PreparedStatement st2= connection.prepareStatement("select referansolan as pd from musteri where referansno=?");
            st2.setInt(1, ikinciref);
            ResultSet executeQuery2 = st2.executeQuery();
            int ucuncuref=0;
            if(executeQuery2.next()) {
                ucuncuref=executeQuery2.getInt("pd");
                
            }
            st2.close();
            executeQuery2.close();    
            System.out.println(ilkref+" "+ikinciref+" "+ucuncuref);
            if(ilkref!=0) {
                updateparapuanwithrefnum(yenitutar,ilkref);
                if(ikinciref!=0) {
                    updateparapuanwithrefnum(yenitutar,ikinciref);
                    if(ucuncuref!=0) {
                    updateparapuanwithrefnum(yenitutar,ucuncuref);
                }
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Odemeyap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
}
