/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.parapuan;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mycompany.parapuan.model.Concatter;
import com.mycompany.parapuan.model.Musteri;
import com.mycompany.parapuan.model.Odeme;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author eray
 */
public class Signin extends javax.swing.JFrame {

    /**
     * Creates new form Signin
     */
    public Signin() {
        initComponents();
        jLabel4.setVisible( false );
        Veritabani.baglan();
        connection = Veritabani.getConnection();
        yedekle();
    }

    Connection connection;

    private void yedekle() {
        List<Musteri> musteriler = new ArrayList();
        List<Odeme> odemeler = new ArrayList();
        try {

            Statement prepareStatement = connection.createStatement();
            ResultSet rs = prepareStatement.executeQuery( "select * from musteri" );

            while (rs.next()) {

                Musteri musteri = new Musteri();
                musteri.setId( rs.getInt( "id" ) );
                musteri.setName( rs.getString( "name" ) );
                musteri.setNumara( rs.getString( "numara" ) );
                musteri.setParapuan( rs.getFloat( "parapuan" ) );
                musteri.setReferansno( rs.getInt( "referansno" ) );
                musteri.setReferansolan( rs.getInt( "referansolan" ) );
                musteriler.add( musteri );

            }
            prepareStatement.close();
            rs.close();

        } catch (SQLException ex) {
            Logger.getLogger( Raporlar.class.getName() ).log( Level.SEVERE, null, ex );
        }

        try {

            Statement prepareStatement = connection.createStatement();
            ResultSet rs = prepareStatement.executeQuery( "select * from odemeler" );

            while (rs.next()) {

                Odeme odeme = new Odeme();
                odeme.setTarih( rs.getDate( "tarih" ) );
                odeme.setTutar( rs.getFloat( "tutar" ) );
                odeme.setTelno( rs.getString( "telno" ) );
                odemeler.add( odeme );

            }
            prepareStatement.close();
            rs.close();

        } catch (SQLException ex) {
            Logger.getLogger( Raporlar.class.getName() ).log( Level.SEVERE, null, ex );
        }

        Concatter concatter = new Concatter();
        concatter.setMusteri( musteriler );
        concatter.setOdeme( odemeler );

        ObjectMapper mapper = new ObjectMapper();
        String json = null;
        try {
            json = mapper.writeValueAsString( concatter );

            
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
        String name = new Date( System.currentTimeMillis() ).toString();

        Path of = Path.of( "/home/stevie/yedek-" + name + ".json" );
        try {
            if ( !Files.exists( of ) ) {
                System.out.println( name );
                Path createFile = Files.createFile( of );
                Files.write( createFile, json.getBytes() );
            }
        } catch (IOException ex) {
            Logger.getLogger( Raporlar.class.getName() ).log( Level.SEVERE, null, ex );
        }


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

        jLabel2.setFont( new java.awt.Font( "Ubuntu", 1, 18 ) ); // NOI18N
        jLabel2.setText( "Kullanıcı Adı :" );

        jLabel3.setFont( new java.awt.Font( "Ubuntu", 1, 18 ) ); // NOI18N
        jLabel3.setText( "Şifre :" );

        username.setName( "" ); // NOI18N
        username.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                usernameActionPerformed( evt );
            }
        } );

        password.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                passwordActionPerformed( evt );
            }
        } );

        jButton1.setFont( new java.awt.Font( "Ubuntu", 0, 18 ) ); // NOI18N
        jButton1.setText( "GİRİŞ YAP" );
        jButton1.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                jButton1ActionPerformed( evt );
            }
        } );

        jLabel4.setForeground( new java.awt.Color( 231, 24, 24 ) );
        jLabel4.setText( "Hatalı kullanıcı adı veya şifre" );

        jLabel1.setFont( new java.awt.Font( "Ubuntu", 1, 24 ) ); // NOI18N
        jLabel1.setText( "SİSTEME GİRİŞ" );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout( jPanel1 );
        jPanel1.setLayout( jPanel1Layout );
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                             .addGroup( jPanel1Layout.createSequentialGroup()
                                                     .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                                             .addGroup( jPanel1Layout.createSequentialGroup()
                                                                                                     .addGap( 198, 198, 198 )
                                                                                                     .addComponent( jLabel4 ) )
                                                                             .addGroup( jPanel1Layout.createSequentialGroup()
                                                                                                     .addGap( 70, 70, 70 )
                                                                                                     .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                                                                                             .addComponent( jLabel2 )
                                                                                                                             .addComponent( jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                                                     .addGap( 68, 68, 68 )
                                                                                                     .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false )
                                                                                                                             .addComponent( username, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE )
                                                                                                                             .addComponent( password ) ) ) )
                                                     .addContainerGap( 153, Short.MAX_VALUE ) )
                             .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                                 .addContainerGap( 218, Short.MAX_VALUE )
                                                                                                 .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                                                                                         .addGroup( jPanel1Layout.createSequentialGroup()
                                                                                                                                                 .addComponent( jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                                                                                                 .addContainerGap() )
                                                                                                                         .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                             .addComponent( jLabel1 )
                                                                                                                                                                                             .addGap( 212, 212, 212 ) ) ) )
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                             .addGroup( jPanel1Layout.createSequentialGroup()
                                                     .addComponent( jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                     .addGap( 21, 21, 21 )
                                                     .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING )
                                                                             .addComponent( jLabel2 )
                                                                             .addComponent( username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                     .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                     .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING )
                                                                             .addComponent( jLabel3 )
                                                                             .addComponent( password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                     .addGap( 33, 33, 33 )
                                                     .addComponent( jButton1 )
                                                     .addGap( 72, 72, 72 )
                                                     .addComponent( jLabel4 )
                                                     .addGap( 130, 130, 130 ) )
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                      .addGroup( layout.createSequentialGroup()
                                       .addContainerGap( 167, Short.MAX_VALUE )
                                       .addComponent( jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE )
                                       .addContainerGap( 169, Short.MAX_VALUE ) )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                      .addGroup( layout.createSequentialGroup()
                                       .addGap( 41, 41, 41 )
                                       .addComponent( jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE )
                                       .addContainerGap( 63, Short.MAX_VALUE ) )
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_jButton1ActionPerformed

        if ( Constants.username.equals( username.getText() ) &&
                Constants.password.equals( String.valueOf( password.getPassword() ) ) ) {

            new Home().setVisible( true );
            dispose();
        } else {
            jLabel4.setVisible( true );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed


    public static void main( String args[] ) {

        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Signin().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
